server:
  port: 8888
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
    show-sql: true

datasource:
  common:
    driver-class-name: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:


